### PR TITLE
intial commit

### PR DESCRIPTION
**Pull request by Yemisirach**
- using good JavaScript best practices
  - using good DRY, KISS, and YAGNI
  - using good HTML & CSS best practices

### CODE REVIEW

**Comment by Kingno3l** [comment]
Hi Remisirach
Good job so far! 
👏👏👏 
You still need to work on some issues to complete this project base on the PR you created, but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- Clean Code✔️ 



 ## Required Changes ♻️

- [ ] **_🛑  Check The Comments Below_**





## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingno3l** [comment]
> Hi Remisirach Good job so far! 👏👏👏 You still need to work on some issues to complete this project base on the PR you created, but you're almost there!
> 
> the-simpsons-homer-simpson [ the-simpsons-homer-simpson ](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif) [ ](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)
> 
> ## To Highlight 🎉
> * Clean Code✔️
> 
> ## Required Changes ♻️
> * [ ]  **_🛑  Check The Comments Below_**
> 
> ## Optional suggestions
> * N/A
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingno3l** [comment]
There are some issues with best practices and maintainability:

- [ ] Use proper HTML 5 semantics tag on your index.html file line **17** to line **19**. Use nav tag or header tag
Screenshot 2023-02-08 at 08 50 53

**Comment by Yemisirach** [comment]
- [ ] Add semantic tag inside index.html file.

**Comment by Kingno3l** [comment]
## Status: Approved ✔️

**Hi  @Yemisirach,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c

You may close this Pull Request and merge the changes
Keep being an awesome dev and success with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Proper use of HTML5 semantics 
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Yemisirach** [comment]
- [ ] Thank you. you can Re-review it again anything you have suggested future.

**Comment by Kingno3l** [comment]
You're Welcome @Yemisirach! 💯 💯💯💯
Congratulations once more... 🎉 🎉 🎉 🎉 

128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c

**Pull request merged**
